file(GLOB_RECURSE COMMON_QT_LIBS_HEADER "${CMAKE_CURRENT_LIST_DIR}/*.h")
file(GLOB_RECURSE COMMON_QT_LIBS_SOURSE "${CMAKE_CURRENT_LIST_DIR}/*.cpp" "${CMAKE_CURRENT_LIST_DIR}/*.ui")

set(COMMON_QT_MAIN_LIBS "${CMAKE_CURRENT_LIST_DIR}/a_debuger.cpp" "${CMAKE_CURRENT_LIST_DIR}/communicationdebuger.cpp" "${CMAKE_CURRENT_LIST_DIR}/communicationdebuger.ui")

set(COMMON_QT_MAIN_UART_LIBS ${COMMON_QT_MAIN_LIBS} "${CMAKE_CURRENT_LIST_DIR}/comportcombobox.cpp" "${CMAKE_CURRENT_LIST_DIR}/uartcommunicationqt.cpp")
